--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: sampleapp
  name: sampleapp-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: sampleapp
  template: 
    metadata: 
      labels: 
        app: sampleapp
    spec: 
      spec: 
      containers: 
      - name: app
        image: "sureshskit/app:latest"
        env: 
        - name: DB2_PORT
          value: "50000"
        - name: DB2_HOST
          value: "db2"
        ports: 
        - containerPort: 9080
        name: http
        ports:
        - containerPort: 9443
        name: https
      imagePullSecrets: 
      - name: regcred

          
        
