apiVersion: v1
kind: Pod
metadata:
  name: sampleapp
spec:
  containers:
  - name: app
    image: sureshskit/app:latest
    ports:
    - containerPort: 9443
      name: https
    - containerPort: 9080
      name: http
  imagePullSecrets:
  - name: regcred
    